theme: jekyll-theme-minimal
title: Ganesh's homepage
description: Bookmark this to keep an eye on my project updates!
twitter_username: GaneshV221
github_username: ganeshv221
email: ganeshv221@gmail.com
